-- ŁAP CHWILE — SUPABASE DATABASE
-- Uruchom ten plik w Supabase -> SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null,
  display_name text,
  avatar_url text,
  bio text,
  created_at timestamptz default now()
);

create table if not exists public.trips (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  country text,
  city text,
  started_at date,
  ended_at date,
  cover_url text,
  created_at timestamptz default now()
);

create table if not exists public.photos (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  trip_id bigint references public.trips(id) on delete set null,
  image_path text not null,
  caption text,
  location text,
  taken_at timestamptz,
  created_at timestamptz default now()
);

create table if not exists public.likes (
  photo_id bigint not null references public.photos(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz default now(),
  primary key(photo_id,user_id)
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  photo_id bigint not null references public.photos(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 1000),
  created_at timestamptz default now()
);

create table if not exists public.follows (
  follower_id uuid not null references public.profiles(id) on delete cascade,
  following_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz default now(),
  primary key(follower_id,following_id),
  check(follower_id <> following_id)
);

alter table public.profiles enable row level security;
alter table public.trips enable row level security;
alter table public.photos enable row level security;
alter table public.likes enable row level security;
alter table public.comments enable row level security;
alter table public.follows enable row level security;

create policy "profiles are public" on public.profiles for select using (true);
create policy "users create own profile" on public.profiles for insert with check (auth.uid()=id);
create policy "users update own profile" on public.profiles for update using (auth.uid()=id);

create policy "trips are public" on public.trips for select using (true);
create policy "users create own trips" on public.trips for insert with check (auth.uid()=user_id);
create policy "users update own trips" on public.trips for update using (auth.uid()=user_id);
create policy "users delete own trips" on public.trips for delete using (auth.uid()=user_id);

create policy "photos are public" on public.photos for select using (true);
create policy "users create own photos" on public.photos for insert with check (auth.uid()=user_id);
create policy "users update own photos" on public.photos for update using (auth.uid()=user_id);
create policy "users delete own photos" on public.photos for delete using (auth.uid()=user_id);

create policy "likes are public" on public.likes for select using (true);
create policy "users add own likes" on public.likes for insert with check (auth.uid()=user_id);
create policy "users remove own likes" on public.likes for delete using (auth.uid()=user_id);

create policy "comments are public" on public.comments for select using (true);
create policy "users add own comments" on public.comments for insert with check (auth.uid()=user_id);
create policy "users delete own comments" on public.comments for delete using (auth.uid()=user_id);

create policy "follows are public" on public.follows for select using (true);
create policy "users follow as self" on public.follows for insert with check (auth.uid()=follower_id);
create policy "users unfollow as self" on public.follows for delete using (auth.uid()=follower_id);

-- Storage bucket for images. If this command is not permitted in your project,
-- create a public bucket named "photos" manually in Storage.
insert into storage.buckets (id, name, public)
values ('photos','photos',true)
on conflict (id) do nothing;

create policy "public photo files are viewable"
on storage.objects for select
using (bucket_id='photos');

create policy "authenticated users upload photos"
on storage.objects for insert
to authenticated
with check (bucket_id='photos');

create policy "users delete their own photo files"
on storage.objects for delete
to authenticated
using (bucket_id='photos' and owner_id=auth.uid()::text);
