(() => {
  const SUPABASE_URL = "https://jcmwjmaywkmnjrciziix.supabase.co";
  const SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjbXdqbWF5d2ttbmpyY2l6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY4ODI4MjQsImV4cCI6MjEwMjQ1ODgyNH0.RtBREQD2r-shvaAJ9tSPR5ypYdIe9pqhwh4QJ3n-ruA";
  const BUCKET = "photos";
  function loadScript(src){return new Promise((resolve,reject)=>{const s=document.createElement("script");s.src=src;s.onload=resolve;s.onerror=()=>reject(new Error("Nie udało się załadować biblioteki logowania."));document.head.appendChild(s);});}
  async function boot(){
    if(!window.supabase?.createClient){try{await loadScript("https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.57.0/dist/umd/supabase.min.js");}catch(_){try{await loadScript("https://unpkg.com/@supabase/supabase-js@2.57.0/dist/umd/supabase.min.js");}catch(e){showFatal("Nie udało się uruchomić modułu logowania. Odśwież stronę i sprawdź połączenie z internetem.");console.error(e);return;}}}
    const supabase=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,flowType:"pkce",storage:window.localStorage,storageKey:"lap-chwile-auth-v6"}});
    const loginButtons=document.querySelectorAll("button.login,button[class*=\"login\"]"),addButtons=document.querySelectorAll("button.add,button[class*=\"add\"]"),gallery=document.querySelector(".gallery"),photoCount=document.querySelector("#photoCount"),uploadStatus=document.querySelector("#uploadStatus"),authModal=document.querySelector("#authModal"),authForm=document.querySelector("#authForm"),authEmail=document.querySelector("#authEmail"),authPassword=document.querySelector("#authPassword"),authSubmit=document.querySelector("#authSubmit"),authSwitch=document.querySelector("#authSwitch"),authClose=document.querySelector("#authClose"),authTitle=document.querySelector("#authTitle"),authSubtitle=document.querySelector("#authSubtitle"),authMessage=document.querySelector("#authMessage");
    let authMode="login",loadingPhotos=false,uploading=false,recoveryLink=null,resendLink=null;
    const setCount=n=>{if(photoCount)photoCount.textContent=n===1?"1 zapisana chwila":`${n} zapisanych chwil`};
    const setUploadStatus=t=>{if(uploadStatus)uploadStatus.textContent=t};
    const clearSavedPhotos=()=>gallery?.querySelectorAll('[data-saved-photo="true"]').forEach(e=>e.remove());
    const updateAuthUI=user=>loginButtons.forEach(b=>{b.textContent=user?"Wyloguj":"Zaloguj";b.dataset.authenticated=user?"true":"false"});
    const setAuthMessage=(t,ok=false)=>{if(authMessage){authMessage.textContent=t;authMessage.className=`auth-message${ok?" ok":""}`}};
    function ensureAuthLinks(){if(!authForm||recoveryLink)return;recoveryLink=document.createElement("button");recoveryLink.type="button";recoveryLink.className="auth-switch";recoveryLink.textContent="Nie pamiętasz hasła? Zresetuj je";recoveryLink.style.display="block";recoveryLink.style.marginTop="8px";recoveryLink.onclick=()=>openAuth("recovery");authForm.insertAdjacentElement("afterend",recoveryLink);resendLink=document.createElement("button");resendLink.type="button";resendLink.className="auth-switch";resendLink.textContent="Wyślij ponownie potwierdzenie e-mail";resendLink.style.display="none";resendLink.style.marginTop="8px";resendLink.onclick=resendConfirmation;recoveryLink.insertAdjacentElement("afterend",resendLink)}
    function openAuth(mode="login"){ensureAuthLinks();authMode=mode;const login=mode==="login",recovery=mode==="recovery";authTitle.textContent=login?"Witaj w Łap Chwilę":recovery?"Odzyskaj dostęp":"Utwórz konto";authSubtitle.textContent=login?"Zaloguj się, aby zachowywać swoje wspomnienia.":recovery?"Podaj e-mail, a wyślemy link do ustawienia nowego hasła.":"Załóż konto i zacznij zachowywać swoje chwile.";authSubmit.textContent=login?"Zaloguj się":recovery?"Wyślij link":"Utwórz konto";authSwitch.textContent=login?"Nie masz konta? Zarejestruj się":"Masz już konto? Zaloguj się";authPassword.style.display=recovery?"none":"block";authPassword.required=!recovery;authForm.querySelector('label[for="authPassword"]')?.style.setProperty("display",recovery?"none":"block");recoveryLink.style.display=login?"block":"none";resendLink.style.display="none";setAuthMessage("");authForm.reset();authModal.classList.add("open");document.body.style.overflow="hidden";setTimeout(()=>authEmail?.focus(),50)}
    function closeAuth(){authModal.classList.remove("open");document.body.style.overflow="";authPassword.style.display="block";authForm.querySelector('label[for="authPassword"]')?.style.setProperty("display","block");setAuthMessage("")}
    const viewer=document.createElement("div");viewer.className="photo-viewer";viewer.innerHTML='<button class="viewer-close" type="button" aria-label="Zamknij">×</button><img class="viewer-image" alt="Powiększone zdjęcie">';document.body.appendChild(viewer);const viewerImage=viewer.querySelector(".viewer-image");const closeViewer=()=>{viewer.classList.remove("open");viewerImage.removeAttribute("src");document.body.style.overflow=""};viewer.onclick=e=>{if(e.target===viewer||e.target.classList.contains("viewer-close"))closeViewer()};
    function addImageToGallery(url,id,imagePath){if(!gallery||gallery.querySelector(`[data-photo-id="${CSS.escape(String(id))}"]`))return;const card=document.createElement("article");card.className="photo-card";card.dataset.savedPhoto="true";card.dataset.photoId=id;const image=document.createElement("img");image.src=url;image.alt="Moja chwila";image.loading="lazy";image.onerror=()=>card.remove();image.onclick=()=>{viewerImage.src=url;viewer.classList.add("open");document.body.style.overflow="hidden"};const button=document.createElement("button");button.className="delete-photo";button.type="button";button.title="Usuń zdjęcie";button.setAttribute("aria-label","Usuń zdjęcie");button.textContent="🗑";button.onclick=()=>deletePhoto(id,imagePath,card);card.append(image,button);gallery.append(card)}
    async function deletePhoto(photoId,imagePath,card){const {data:{user}}=await supabase.auth.getUser();if(!user||!photoId||!imagePath)return;if(!confirm("Usunąć tę chwilę? Tej operacji nie można cofnąć."))return;const {error}=await supabase.from("photos").delete().eq("id",photoId).eq("user_id",user.id);if(error)return setUploadStatus(`Nie udało się usunąć zdjęcia: ${error.message}`);await supabase.storage.from(BUCKET).remove([imagePath]);card?.remove();setCount(gallery?.querySelectorAll('[data-saved-photo="true"]').length||0)}
    async function loadSavedPhotos(){if(loadingPhotos)return;loadingPhotos=true;try{const {data:{user},error:userError}=await supabase.auth.getUser();if(userError||!user){clearSavedPhotos();setCount(0);return}const {data,error}=await supabase.from("photos").select("id,image_path,caption,created_at").eq("user_id",user.id).order("created_at",{ascending:false});if(error){console.error("photos select:",error);setUploadStatus(`Nie udało się wczytać zapisanych chwil: ${error.message}`);return}clearSavedPhotos();const seen=new Set();(data||[]).forEach(photo=>{if(seen.has(photo.image_path))return;seen.add(photo.image_path);const {data:publicData}=supabase.storage.from(BUCKET).getPublicUrl(photo.image_path);addImageToGallery(publicData.publicUrl,photo.id,photo.image_path)});setCount(seen.size)}finally{loadingPhotos=false}}
    async function sha256(file){const digest=await crypto.subtle.digest("SHA-256",await file.arrayBuffer());return Array.from(new Uint8Array(digest)).map(b=>b.toString(16).padStart(2,"0")).join("")}
    async function uploadOne(file,user){if(!file.type.startsWith("image/"))throw new Error("To nie jest zdjęcie.");if(file.size>10*1024*1024)throw new Error(`${file.name}: maks. 10 MB.`);const hash=await sha256(file),extension=(file.name.split(".").pop()||"jpg").toLowerCase().replace(/[^a-z0-9]/g,"")||"jpg",filePath=`${user.id}/${hash}.${extension}`;const {data:existing,error:existingError}=await supabase.from("photos").select("id").eq("user_id",user.id).eq("image_path",filePath).limit(1);if(existingError)throw existingError;if(existing?.length)return false;const {error:uploadError}=await supabase.storage.from(BUCKET).upload(filePath,file,{cacheControl:"3600",upsert:false,contentType:file.type});if(uploadError){if(String(uploadError.message||"").toLowerCase().includes("already exists"))return false;throw uploadError}const {error:dbError}=await supabase.from("photos").insert({user_id:user.id,image_path:filePath,caption:""});if(dbError){await supabase.storage.from(BUCKET).remove([filePath]);if(String(dbError.code||"").startsWith("23")||String(dbError.message||"").toLowerCase().includes("duplicate"))return false;throw dbError}return true}
    async function uploadPhotos(files){if(uploading)return;uploading=true;try{const {data:{user},error}=await supabase.auth.getUser();if(error||!user)return openAuth("login");const valid=Array.from(files||[]).filter(f=>f.type.startsWith("image/")&&f.size<=10*1024*1024);if(!valid.length)return alert("Wybierz zdjęcia do 10 MB każde.");setUploadStatus(`Przesyłanie 0/${valid.length} zdjęć…`);let done=0,skipped=0,failed=0;const hashes=new Set();for(const file of valid){try{const hash=await sha256(file);if(hashes.has(hash)){skipped++;continue}hashes.add(hash);if(await uploadOne(file,user))done++;else skipped++;setUploadStatus(`Przesyłanie ${done+skipped}/${valid.length} zdjęć…`)}catch(error){failed++;console.error(error)}}await loadSavedPhotos();setUploadStatus(failed?`Dodano ${done}. Pominięto ${skipped}. Błędy: ${failed}.`:`Gotowe — dodano ${done}, pominięto ${skipped}.`)}finally{uploading=false}}
    async function resendConfirmation(){const email=authEmail.value.trim();if(!email)return setAuthMessage("Najpierw wpisz swój e-mail.");resendLink.disabled=true;try{const {error}=await supabase.auth.resend({type:"signup",email,options:{emailRedirectTo:window.location.origin}});if(error)throw error;setAuthMessage("Wysłaliśmy ponownie wiadomość potwierdzającą. Sprawdź skrzynkę i spam.",true)}catch(error){setAuthMessage(String(error?.message||"Nie udało się wysłać wiadomości."))}finally{resendLink.disabled=false}}
    async function sendRecovery(){const email=authEmail.value.trim();if(!email)return setAuthMessage("Podaj adres e-mail.");const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin});if(error)throw error;setAuthMessage("Link do ustawienia nowego hasła został wysłany. Sprawdź e-mail i spam.",true)}
    addButtons.forEach(button=>button.addEventListener("click",async e=>{e.preventDefault();if(uploading)return;try{const {data:{user},error}=await supabase.auth.getUser();if(error||!user)return openAuth("login");const input=document.createElement("input");input.type="file";input.accept="image/*";input.multiple=true;input.onchange=()=>input.files?.length&&uploadPhotos(input.files);input.click()}catch(error){setUploadStatus(`Błąd sesji: ${error?.message||"spróbuj ponownie"}`)}}));
    loginButtons.forEach(button=>button.addEventListener("click",async e=>{e.preventDefault();try{const {data:{session},error}=await supabase.auth.getSession();if(error)throw error;if(session){await supabase.auth.signOut();updateAuthUI(null);clearSavedPhotos();setCount(0);setUploadStatus("")}else openAuth("login")}catch(error){console.error(error);openAuth("login");setAuthMessage(`Nie udało się sprawdzić sesji: ${error?.message||"spróbuj ponownie"}`)}}));
    authClose.addEventListener("click",closeAuth);authModal.addEventListener("click",e=>e.target===authModal&&closeAuth());authSwitch.addEventListener("click",()=>openAuth(authMode==="login"?"signup":"login"));
    authForm.addEventListener("submit",async e=>{e.preventDefault();const email=authEmail.value.trim(),password=authPassword.value;if(!email)return setAuthMessage("Podaj e-mail.");if(authMode!=="recovery"&&!password)return setAuthMessage("Podaj hasło.");authSubmit.disabled=true;setAuthMessage(authMode==="recovery"?"Wysyłanie linku…":"Łączenie z kontem…",true);try{if(authMode==="recovery")await sendRecovery();else if(authMode==="login"){const result=await Promise.race([supabase.auth.signInWithPassword({email,password}),new Promise((_,reject)=>setTimeout(()=>reject(new Error("Logowanie trwa zbyt długo. Sprawdź połączenie i spróbuj ponownie.")),15000))]);if(result.error)throw result.error;if(!result.data?.session)throw new Error("Serwer nie zwrócił aktywnej sesji.");updateAuthUI(result.data.user);closeAuth();await loadSavedPhotos()}else{const {data,error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:window.location.origin}});if(error)throw error;if(data.session){updateAuthUI(data.user);closeAuth();await loadSavedPhotos()}else{resendLink.style.display="block";setAuthMessage("Konto utworzone. Sprawdź e-mail, aby potwierdzić adres.",true)}}}catch(error){console.error("Auth error:",error);const message=String(error?.message||"Wystąpił błąd logowania."),lower=message.toLowerCase();if(lower.includes("email not confirmed")){setAuthMessage("Ten adres e-mail nie został jeszcze potwierdzony. Sprawdź skrzynkę lub wyślij wiadomość ponownie.");resendLink.style.display="block"}else if(lower.includes("invalid login credentials"))setAuthMessage("Nieprawidłowy e-mail lub hasło. Jeśli nie pamiętasz hasła, użyj opcji „Zresetuj je”.");else if(lower.includes("too many requests")||lower.includes("rate limit"))setAuthMessage("Za dużo prób w krótkim czasie. Odczekaj chwilę i spróbuj ponownie.");else setAuthMessage(message)}finally{authSubmit.disabled=false;authSubmit.textContent=authMode==="login"?"Zaloguj się":authMode==="recovery"?"Wyślij link":"Utwórz konto"}});
    document.addEventListener("keydown",e=>{if(e.key==="Escape"){closeViewer();closeAuth()}});ensureAuthLinks();
    supabase.auth.onAuthStateChange((event,session)=>{console.info("Supabase auth event:",event,Boolean(session));updateAuthUI(session?.user??null);if(session?.user)setTimeout(loadSavedPhotos,0);else{clearSavedPhotos();setCount(0)}});
    try{const {data:{session},error}=await supabase.auth.getSession();if(error)throw error;updateAuthUI(session?.user??null);if(session?.user)await loadSavedPhotos()}catch(error){console.error("Initial auth check:",error);updateAuthUI(null);setUploadStatus(`Logowanie nie zostało uruchomione: ${error?.message||"spróbuj ponownie"}`)}
  }
  function showFatal(message){const button=document.querySelector("button.login"),status=document.querySelector("#uploadStatus");if(button)button.textContent="Błąd logowania";if(status)status.textContent=message;console.error(message)}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();
})();